name: Hello World

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  job1:
    name: Primeiro Job
    runs-on: ubuntu-latest

    steps:
      - name: Passo 1
        run: env | sort
  
  job2:
    name: Segundo Job
    runs-on: windows-latest
    steps:
      - name: Passo 1
        run: "Get-ChildItem Env: | Sort-Object Name"
        
  job3:
    name: Terceiro Job
    runs-on: macos-latest
    
    steps:
      - name: Passo 1
        run: env | sort
  
  
  job4:
    name: Quarto Job
    runs-on: depend-latest
    needs: [job1, job2,job3]
    
    steps:
      - name: Ultimo passo
        run: echo job1
